[package]
name = "sekai"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
axum = "0.8.7"
tower-http = { version = "0.6.8", features = [
    "cors",
    "compression-gzip",
    "trace",
    "normalize-path",
] }
tower = "0.5.3"
serde = { version = "1.0.228", features = ["derive"] }
futures-util = "0.3.31"
