CREATE TABLE IF NOT EXISTS file_metadata (
    id NUMERIC(39, 0) PRIMARY KEY,
    file_name VARCHAR(256) NOT NULL
);

CREATE UNIQUE INDEX file_metadata_idx ON file_metadata(id);

CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    bio TEXT NOT NULL DEFAULT '',
    is_admin BOOLEAN NOT NULL DEFAULT false,
    points BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX user_idx ON users(id);

CREATE TABLE IF NOT EXISTS posts (
    id NUMERIC(39, 0) PRIMARY KEY,
    author UUID NOT NULL REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    content TEXT NOT NULL DEFAULT '',
    likes BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX post_idx ON posts(id);

CREATE TABLE post_attachments (
    post_id NUMERIC(39, 0) REFERENCES posts(id) ON UPDATE CASCADE ON DELETE CASCADE,
    attachment_id NUMERIC(39, 0) REFERENCES file_metadata(id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (post_id, attachment_id)
);

CREATE UNIQUE INDEX post_attachment_idx ON post_attachments(post_id, attachment_id);